server:
  port: 8000
  servlet:
    context-path: /interauto
logging:
  level:
    root: debug
  config: classpath:profiles/log4j2/log4j2-test.xml


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.227:3306/interauto?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT-8&useAffectedRows=true
    username: auto
    password: 688451a

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.com.honda.interauto.dao
